export type StepType='teoria'|'spotlight-app'|'spotlight-diagrama'|'spotlight-codigo';
export type Step={id:number;capitulo:number;tipo:StepType;ator?:'cliente'|'atendente'|'ambos';titulo:string;conteudo?:string[];alvo?:string;badge?:string;fonte:string;opcional?:boolean};
const T=(id:number,capitulo:number,titulo:string,conteudo:string[],fonte:string,opcional=false):Step=>({id,capitulo,tipo:'teoria',titulo,conteudo,fonte,opcional});
const A=(id:number,capitulo:number,titulo:string,ator:'cliente'|'atendente'|'ambos',alvo:string,badge:string,fonte:string,opcional=false):Step=>({id,capitulo,tipo:'spotlight-app',titulo,ator,alvo,badge,fonte,opcional});
const D=(id:number,capitulo:number,titulo:string,alvo:string,fonte:string,opcional=false):Step=>({id,capitulo,tipo:'spotlight-diagrama',titulo,alvo,fonte,opcional});
const C=(id:number,capitulo:number,titulo:string,alvo:string,fonte:string,opcional=false):Step=>({id,capitulo,tipo:'spotlight-codigo',titulo,alvo,fonte,opcional});
export const steps:Step[]=[
T(1,0,'Sistema Unespão',['Plataforma de pedidos personalizados para padarias','Engenharia de Software II · UNESP Bauru · 2026','Um tour visual por arquitetura, componentes, UX, testes e entrega'],'Capa do documento'),
T(2,1,'O problema que estamos resolvendo',['Personalização hoje acontece sem suporte informatizado.','Cliente e Atendente/Administrador precisam compartilhar o mesmo fluxo.','O sistema transforma escolhas em um pedido rastreável.'],'Cap. 1.1'),A(3,1,'A experiência em uma só visão','ambos','preview','EM FOCO NA APLICAÇÃO: Cliente + Atendente','Cap. 1.1',true),T(4,1,'Escopo e requisitos',['Dentro: pedidos personalizados, catálogo, estoque, pagamento e avaliação.','Fora: dependência de um backend real nesta demonstração.','Requisitos-chave orientam cada decisão de design.'],'Cap. 1.2, 1.3'),T(5,1,'Objetivos de qualidade',['Prioridade alta: usabilidade, desempenho, segurança e manutenibilidade.','Prioridade média: escalabilidade e portabilidade.'],'Cap. 1.4'),
T(6,2,'Fronteiras do sistema',['Uma loja, dois atores e três sistemas externos.','O Unespão conecta escolhas do cliente às operações da padaria.'],'Cap. 2.1'),D(7,2,'Diagrama de Contexto C4 Nível 1','context','Cap. 2.1, Fig. 2.1'),T(8,2,'Arquitetura em camadas',['Clean Architecture organiza responsabilidades em camadas concêntricas.','O Diagrama de Containers torna as fronteiras executáveis.'],'Cap. 2.2, 2.3'),D(9,2,'Diagrama de Containers C4 Nível 2','containers','Cap. 2.3, Fig. 2.2',true),T(10,2,'Decisões e restrições',['Stack definida pelo projeto e integrações obrigatórias.','A arquitetura reduz acoplamento e preserva pontos de troca.'],'Cap. 2.4, 2.5'),
T(11,3,'Seis grupos de componentes',['Domínio · Aplicação · Infraestrutura · Apresentação · Integrações · Dados.','Cada grupo tem uma responsabilidade clara.'],'Cap. 3.1'),D(12,3,'Diagrama de classes simplificado','classes','Cap. 3.2, Fig. 3.1'),T(13,3,'Princípios SOLID',['Responsabilidade única e aberto/fechado guiam a evolução.','Inversão de dependência mantém o domínio independente.'],'Cap. 3.3'),C(14,3,'Construtor de PedidoService','pedido-service','Cap. 3.3, Listing 3.1'),T(15,3,'Repository & Adapter',['Repository abstrai persistência.','Adapter traduz contratos externos sem contaminar o domínio.'],'Cap. 3.4'),D(16,3,'Adapter aplicado ao pagamento','adapter','Cap. 3.4, Fig. 3.3'),T(17,3,'DI & Strategy',['Injeção de dependência permite trocar o gateway.','Strategy encapsula comportamentos alternativos.'],'Cap. 3.4'),C(18,3,'IGatewayPagamentoAdapter','gateway-interface','Cap. 3.4',true),T(19,3,'Decorator para ingredientes',['Cada ingrediente adiciona comportamento e preço.','A composição evita uma explosão de subclasses.'],'Cap. 3.4'),A(20,3,'Demo ao vivo: montar o lanche','cliente','decorator','EM FOCO NA APLICAÇÃO: Cardápio & Montagem','Cap. 3.4, Fig. 3.4'),
T(21,4,'Canais do Cliente',['Totem e app percorrem um fluxo de oito passos.','A mesma experiência é clara, rápida e personalizável.'],'Cap. 4.1, 4.2, 4.3'),A(22,4,'Cardápio & montagem','cliente','menu','EM FOCO NA APLICAÇÃO: Cardápio & Montagem','Cap. 4.3, Fig. 4.1'),T(23,4,'Identificação no totem',['QR code agiliza o retorno de um cliente.','Pedido anônimo mantém a jornada acessível.'],'Cap. 4.4'),A(24,4,'Identificação por QR code','cliente','qr','EM FOCO NA APLICAÇÃO: Identificação do Cliente','Cap. 4.4, Fig. 4.3'),T(25,4,'Montagem, personalização e revisão',['Os passos 2–4 organizam escolha, extras e conferência.','O carrinho visto no capítulo anterior reaparece aqui.'],'Cap. 4.3'),A(26,4,'Resumo e revisão','cliente','review','EM FOCO NA APLICAÇÃO: Revisão do Pedido','Cap. 4.3, Fig. 4.1'),T(27,4,'Pagamento e confirmação',['Os passos 5–8 fecham pagamento, confirmação, avaliação e sugestões.','Cada retorno reforça confiança.'],'Cap. 4.3'),A(28,4,'Pagamento e confirmação','cliente','payment','EM FOCO NA APLICAÇÃO: Pagamento','Cap. 4.3'),T(29,4,'Operação do Atendente',['Catálogo e estoque dão visibilidade para quem prepara o pedido.','Dados fictícios nesta simulação deixam a interface demonstrável.'],'Cap. 4.5'),A(30,4,'Catálogo & estoque','atendente','staff','EM FOCO NA APLICAÇÃO: Atendente','Cap. 4.5'),
T(31,5,'A pirâmide de testes',['Unidade: rápida e numerosa.','Integração: contratos entre componentes.','Sistema: comportamento completo.'],'Cap. 5.1'),D(32,5,'Pirâmide de testes','tests','Cap. 5.1, Fig. 5.1'),T(33,5,'Mocks e LSP',['Moq isola dependências nos testes unitários.','PedidoRepository e MockPedidoRepository respeitam o mesmo contrato.'],'Cap. 5.2'),C(34,5,'Teste de PedidoService com Moq','moq-test','Cap. 5.2, Listing 5.2'),T(35,5,'Critérios e métricas',['Conclusão combina cobertura, cenários aprovados e critérios de qualidade.','A medição torna a entrega verificável.'],'Cap. 5.5'),C(36,5,'Cenário Playwright com QR code','playwright','Cap. 5.4, 5.5, Listing 5.8',true),
T(37,6,'Configuração e manutenção',['Versionar código e dependências.','Manter segredos fora do repositório.'],'Cap. 6.1, 6.2'),D(38,6,'Do placeholder à variável de ambiente','secrets','Cap. 6.1',true),T(39,6,'Rastreabilidade',['Issue ↔ PR ↔ Testes cria uma linha de evidência.','Cada mudança permanece explicável.'],'Cap. 6.3'),D(40,6,'Fluxo de Pull Requests','prs','Cap. 6.3, Fig. 6.1'),T(41,6,'Build, integração e entrega',['CI/CD automatiza verificação e entrega.','O pipeline transforma commits em confiança.'],'Cap. 6.4'),D(42,6,'Pipeline de CI/CD','cicd','Cap. 6.4',true),
T(43,7,'Recapitulação e perguntas',['Uma plataforma: do problema à entrega.','Seis capítulos conectados por uma experiência única.','Obrigado — perguntas?'],'Síntese')
];
export const chapters=[{n:0,label:'Capa'},{n:1,label:'Introdução'},{n:2,label:'Arquitetura'},{n:3,label:'Componentes'},{n:4,label:'Interface'},{n:5,label:'Testes'},{n:6,label:'Manutenção'},{n:7,label:'Encerramento'}];
